=== EPFL-Infoscience/dspace-cris/dspace/config/submission-forms.dtd
<!-- DSpace Custom Submit input form definition language -->


 <!ELEMENT input-forms (form-definitions, form-value-pairs) >

 <!ELEMENT form-definitions (form)+ >
 <!ELEMENT form (row)+ >
 <!ELEMENT row (field|relation-field)+ >
 <!ATTLIST form name NMTOKEN #REQUIRED>

 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, label, input-type, repeatable?, required?, style?, language?, hint, type-bind?, regex?, vocabulary?, visibility?, readonly?) >
 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 <!ELEMENT language (#PCDATA)>
 <!ELEMENT type-bind (#PCDATA) >

 <!ELEMENT repeatable (#PCDATA) >
 <!ELEMENT label (#PCDATA) >
 <!ELEMENT style (#PCDATA) >
 <!ELEMENT input-type (#PCDATA)>

 <!ELEMENT hint (#PCDATA) >
 <!ELEMENT required (#PCDATA)>
 <!ELEMENT name-variants (#PCDATA)>
 <!ELEMENT regex (#PCDATA) >

 <!ELEMENT form-value-pairs (value-pairs)* >
 <!ELEMENT value-pairs (pair)+ >

 <!-- ***
        To assign a particular 'value-pairs' list to a particular dropdown 'input-type'
        field, as found on a particular form, put:
        - value-pairs/@value-pairs-name string into
           form/page/field/input-type/@value-pairs-name
        - form/page/field/@DCelement + '_' + form/field/DCqualifier into
           value-pairs/@dc-term
             (e.g. 'language_iso')
  -->
 <!ATTLIST value-pairs value-pairs-name CDATA #REQUIRED
                            dc-term   CDATA #REQUIRED
 >

 <!ELEMENT pair (displayed-value,stored-value) >
 <!ELEMENT displayed-value (#PCDATA)>
 <!ELEMENT stored-value (#PCDATA)>

 <!ATTLIST input-type value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT vocabulary (#PCDATA) >

 <!ATTLIST vocabulary closed (true|false) "false">

 <!ELEMENT visibility (#PCDATA) >

 <!ATTLIST language value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT readonly (#PCDATA) >

<!ELEMENT relationship-type (#PCDATA) >
<!ELEMENT search-configuration (#PCDATA) >
<!ELEMENT filter (#PCDATA) >
<!ELEMENT externalsources (#PCDATA) >
<!ELEMENT relation-field (relationship-type, search-configuration, filter?, repeatable?, name-variants?, label, type-bind?, hint, linked-metadata-field?, externalsources?, required?, regex?, visibility?)>
<!ELEMENT linked-metadata-field (dc-schema, dc-element, dc-qualifier?, input-type)>

=== EPFL-Infoscience/dspace-cris/dspace-api/src/test/data/dspaceFolder/config/submission-forms.xml
<?xml version="1.0"?>
<!DOCTYPE input-forms SYSTEM "submission-forms.dtd">


<input-forms>

 <!-- The form-definitions map lays out the detailed definition of all the -->
 <!-- submission forms. Each separate form set has a unique name as an     -->
 <!-- attribute. This name matches one of the names in the form-map. One   -->
 <!-- named form set has the name "traditional"; as this name suggests,    -->
 <!-- it is the old style and is also the default, which gets used when    -->
 <!-- the specified collection has no correspondingly-named form set.      -->
 <!--                                                                      -->
 <!-- Each form set contains an ordered set of pages; each page defines    -->
 <!-- one submission metadata entry screen. Each page has an ordered list  -->
 <!-- of field definitions, Each field definition corresponds to one       -->
 <!-- metadata entry (a so-called row), which has a DC element name, a     -->
 <!-- displayed label, a text string prompt which is called a hint, and    -->
 <!-- an input-type. Each field also may hold optional elements: DC        -->
 <!-- qualifier name, a repeatable flag, an optional name-variants allowed -->
 <!-- flag, and a text string whose presence serves as a                   -->
 <!-- 'this field is required' flag.                                       -->

 <form-definitions>
    <form name="bitstream-metadata">
	<row>
	       <field>
	         <dc-schema>dc</dc-schema>
	         <dc-element>title</dc-element>
	         <dc-qualifier></dc-qualifier>
	         <repeatable>false</repeatable>
	         <label>Title</label>
	         <input-type>onebox</input-type>
	         <hint>Enter the name of the file.</hint>
	         <required>You must enter a main title for this item.</required>
	       </field>
	</row>
	<row>
	       <field>
	         <dc-schema>dc</dc-schema>
	         <dc-element>description</dc-element>
	         <repeatable>true</repeatable>
	         <label>Description</label>
	         <input-type>textarea</input-type>
	         <hint>Enter a description for the file</hint>
	         <required></required>
	       </field>
       </row>
   </form>

   <form name="traditionalpageone">
            <!-- NOTE: this Author <row> is customized from the default submission-forms.xml in order to make it
                 easier to test Entity functionality -->
            <row>
                <relation-field>
                    <relationship-type>isAuthorOfPublication</relationship-type>
                    <search-configuration>person</search-configuration>
                    <repeatable>true</repeatable>
                    <name-variants>true</name-variants>
                    <label>Author</label>
                    <hint>Add an author</hint>
                    <linked-metadata-field>
                        <dc-schema>dc</dc-schema>
                        <dc-element>contributor</dc-element>
                        <dc-qualifier>author</dc-qualifier>
                        <input-type>name</input-type>
                    </linked-metadata-field>
                    <externalsources>orcid,my_staff_db</externalsources>
                    <required></required>
                </relation-field>
            </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>title</dc-element>
         <dc-qualifier></dc-qualifier>
         <repeatable>false</repeatable>
         <label>Title</label>
         <input-type>onebox</input-type>
         <hint>Enter the main title of the item.</hint>
         <required>You must enter a main title for this item.</required>
         <!--    <language value-pairs-name="common_iso_languages">true</language> -->
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>title</dc-element>
         <dc-qualifier>alternative</dc-qualifier>
         <repeatable>true</repeatable>
         <label>Other Titles</label>
         <input-type>onebox</input-type>
         <hint>If the item has any alternative titles, please enter them here.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>date</dc-element>
         <dc-qualifier>issued</dc-qualifier>
         <repeatable>false</repeatable>
         <label>Date of Issue</label>
         <style>col-sm-4</style>
         <input-type>date</input-type>
         <hint>Please give the date of previous publication or public distribution.
                        You can leave out the day and/or month if they aren't
                        applicable.</hint>
         <required>You must enter at least the year.</required>
       </field>

       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>publisher</dc-element>
         <dc-qualifier></dc-qualifier>
         <repeatable>false</repeatable>
         <label>Publisher</label>
         <style>col-sm-8</style>
         <input-type>onebox</input-type>
         <hint>Enter the name of the publisher of the previously issued instance of this item.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>identifier</dc-element>
         <dc-qualifier>citation</dc-qualifier>
         <repeatable>false</repeatable>
         <label>Citation</label>
         <input-type>onebox</input-type>
         <hint>Enter the standard citation for the previously issued instance of this item.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>relation</dc-element>
         <dc-qualifier>ispartofseries</dc-qualifier>
         <repeatable>true</repeatable>
         <label>Series/Report No.</label>
         <type-bind>Technical Report</type-bind>
         <input-type>series</input-type>
         <hint>Enter the series and number assigned to this item by your community.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>identifier</dc-element>
         <dc-qualifier></dc-qualifier>
         <!-- An input-type of qualdrop_value MUST be marked as repeatable -->
         <repeatable>true</repeatable>
         <label>Identifiers</label>
         <input-type value-pairs-name="common_identifiers">qualdrop_value</input-type>
         <hint>If the item has any identification numbers or codes associated with
it, please enter the types and the actual numbers or codes.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>type</dc-element>
         <dc-qualifier></dc-qualifier>
         <repeatable>true</repeatable>
         <label>Type</label>
         <input-type value-pairs-name="common_types">dropdown</input-type>
         <hint>Select the type(s) of content of the item. To select more than one value in the list, you may have to hold down the "CTRL" or "Shift" key.</hint>
         <required></required>
       </field>
     </row>
     <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>language</dc-element>
         <dc-qualifier>iso</dc-qualifier>
         <repeatable>false</repeatable>
         <label>Language</label>
         <input-type value-pairs-name="common_iso_languages">dropdown</input-type>
         <hint>Select the language of the main content of the item.  If the language does not appear in the list, please select 'Other'.  If the content does not really have a language (for example, if it is a dataset or an image) please select 'N/A'.</hint>
         <required></required>
       </field>
     </row>
	</form>

    <form name="traditionalpageone-cris-dc-contributor-author">
      <row>
        <field>
          <dc-schema>dc</dc-schema>
          <dc-element>contributor</dc-element>
          <dc-qualifier>author</dc-qualifier>
          <label>Author</label>
          <input-type>name</input-type>
          <repeatable>false</repeatable>
          <required>You must enter at least the author.</required>
          <hint>Enter the names of the authors of this item in the form Lastname, Firstname [i.e. Smith, Josh or Smith, J].</hint>
        </field>
      </row>
      <row>
        <field>
          <dc-schema>person</dc-schema>
          <dc-element>affiliation</dc-element>
          <dc-qualifier>name</dc-qualifier>
          <label>Affiliation</label>
          <input-type>onebox</input-type>
          <repeatable>false</repeatable>
          <required />
          <hint>Enter the affiliation of the author as stated on the publication.</hint>
        </field>
      </row>
    </form>

    <form name="traditionalpageone-cris-orgunit-identifier-name">
      <row>
        <field>
         <dc-schema>orgunit</dc-schema>
         <dc-element>identifier</dc-element>
         <dc-qualifier>name</dc-qualifier>
          <label>Orgunit name</label>
          <input-type>onebox</input-type>
          <repeatable>false</repeatable>
          <required>You must enter at least the Orgunit name.</required>
          <hint>Enter the name of the Orgunit of this item</hint>
        </field>
      </row>
      <row>
        <field>
         <dc-schema>orgunit</dc-schema>
         <dc-element>identifier</dc-element>
         <dc-qualifier>id</dc-qualifier>
          <label>Orgunit id</label>
          <input-type>onebox</input-type>
          <repeatable>false</repeatable>
          <required />
          <hint>Enter the id of the Orgunit of this item</hint>
        </field>
      </row>
    </form>

   <form name="traditionalpageone-cris">
	 <row>
       <field>
         <dc-schema>dc</dc-schema>
         <dc-element>contributor</dc-element>
         <dc-qualifier>author</dc-qualifier>
         <repeatable>true</repeatable>
         <label>Authors</label>
